/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleJNIForCppChecking */

#ifndef _Included_SampleJNIForCppChecking
#define _Included_SampleJNIForCppChecking
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleJNIForCppChecking
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleJNIForCppChecking_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
