/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowEventJava */

#ifndef _Included_WindowEventJava
#define _Included_WindowEventJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowEventJava
 * Method:    printEventViewer
 * Signature: ()[Ljava/util/Properties;
 */
JNIEXPORT jobjectArray JNICALL Java_WindowEventJava_printEventViewer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
