/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaApplication */

#ifndef _Included_JavaApplication
#define _Included_JavaApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaApplication
 * Method:    basedonDate
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_JavaApplication_basedonDate
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     JavaApplication
 * Method:    basedonUser
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_JavaApplication_basedonUser
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
